import type {
  ActivityItem,
  BudgetDatum,
  Deadline,
  Department,
  DependencyEdgeData,
  DependencyNodeData,
  HeatmapCell,
  HeatmapMetric,
  HealthStatus,
  KpiMetric,
  MonthlyFinancialDatum,
  Person,
  PortfolioSlice,
  Project,
  ProjectStatus,
  Risk,
  Task,
  TaskTrendDatum,
  WorkloadDatum,
} from "./types";

export const dashboardSnapshotAt = "2026-07-17T09:30:00+02:00";

export const teamMembers: Person[] = [
  { id: "person-elena", name: "Elena Marquez", initials: "EM", title: "Chief Operating Officer" },
  { id: "person-marcus", name: "Marcus Chen", initials: "MC", title: "VP, Finance" },
  { id: "person-priya", name: "Priya Nair", initials: "PN", title: "VP, Revenue" },
  { id: "person-jonas", name: "Jonas Berg", initials: "JB", title: "VP, Product" },
  { id: "person-aisha", name: "Aisha Rahman", initials: "AR", title: "VP, Technology" },
  { id: "person-sofia", name: "Sofia Alvarez", initials: "SA", title: "VP, People" },
  { id: "person-lena", name: "Lena Ortiz", initials: "LO", title: "Director, Operations Programs" },
  { id: "person-daniel", name: "Daniel Kim", initials: "DK", title: "Director, Business Systems" },
  { id: "person-amara", name: "Amara Okafor", initials: "AO", title: "Director, Enterprise Sales" },
  { id: "person-theo", name: "Theo Martin", initials: "TM", title: "Group Product Manager" },
  { id: "person-noah", name: "Noah Williams", initials: "NW", title: "Director, Data Platform" },
  { id: "person-mei", name: "Mei Tan", initials: "MT", title: "Director, Talent Operations" },
  { id: "person-olivia", name: "Olivia Rossi", initials: "OR", title: "Senior Program Manager" },
  { id: "person-samuel", name: "Samuel Adeyemi", initials: "SA", title: "Finance Transformation Lead" },
  { id: "person-isabel", name: "Isabel Costa", initials: "IC", title: "Customer Operations Lead" },
  { id: "person-viktor", name: "Viktor Novak", initials: "VN", title: "Principal Engineer" },
  { id: "person-hana", name: "Hana Suzuki", initials: "HS", title: "Revenue Operations Lead" },
  { id: "person-mateo", name: "Mateo Silva", initials: "MS", title: "Product Operations Lead" },
];

const getPerson = (id: string): Person => {
  const member = teamMembers.find((person) => person.id === id);
  if (!member) throw new Error(`Unknown team member: ${id}`);
  return member;
};

export const departments: Department[] = [
  {
    id: "operations",
    name: "Operations",
    shortName: "Ops",
    color: "#0EA5E9",
    leaderId: "person-elena",
    headcount: 42,
    annualBudget: 5_200_000,
    description: "Customer delivery, procurement, and service quality.",
  },
  {
    id: "finance",
    name: "Finance",
    shortName: "Fin",
    color: "#8B5CF6",
    leaderId: "person-marcus",
    headcount: 18,
    annualBudget: 2_400_000,
    description: "Planning, accounting, treasury, and business systems.",
  },
  {
    id: "sales",
    name: "Revenue",
    shortName: "Rev",
    color: "#22C55E",
    leaderId: "person-priya",
    headcount: 38,
    annualBudget: 4_800_000,
    description: "Enterprise sales, partnerships, and revenue operations.",
  },
  {
    id: "product",
    name: "Product",
    shortName: "Prod",
    color: "#F59E0B",
    leaderId: "person-jonas",
    headcount: 31,
    annualBudget: 6_100_000,
    description: "Product strategy, design, research, and delivery.",
  },
  {
    id: "technology",
    name: "Technology",
    shortName: "Tech",
    color: "#6366F1",
    leaderId: "person-aisha",
    headcount: 39,
    annualBudget: 7_400_000,
    description: "Platform engineering, data, security, and reliability.",
  },
  {
    id: "people",
    name: "People",
    shortName: "People",
    color: "#EC4899",
    leaderId: "person-sofia",
    headcount: 16,
    annualBudget: 2_100_000,
    description: "Talent, leadership development, and employee experience.",
  },
];

export const kpiMetrics: KpiMetric[] = [
  {
    id: "monthly-revenue",
    label: "Monthly revenue",
    value: 2_840_000,
    formattedValue: "$2.84M",
    format: "currency",
    change: 12.4,
    changeLabel: "+12.4%",
    trend: "up",
    favorable: true,
    comparisonLabel: "vs. Jul 2025",
    target: 2_750_000,
    formattedTarget: "$2.75M target",
    targetProgress: 103.3,
    description: "Revenue is $90K ahead of the July operating plan.",
    sparkline: [
      { label: "W20", value: 610_000 },
      { label: "W21", value: 648_000 },
      { label: "W22", value: 632_000 },
      { label: "W23", value: 675_000 },
      { label: "W24", value: 691_000 },
      { label: "W25", value: 704_000 },
      { label: "W26", value: 716_000 },
      { label: "W27", value: 729_000 },
    ],
  },
  {
    id: "operating-margin",
    label: "Operating margin",
    value: 24.8,
    formattedValue: "24.8%",
    format: "percent",
    change: 2.1,
    changeLabel: "+2.1 pts",
    trend: "up",
    favorable: true,
    comparisonLabel: "vs. prior quarter",
    target: 23,
    formattedTarget: "23.0% target",
    targetProgress: 107.8,
    description: "Services mix and cloud savings lifted margin above plan.",
    sparkline: [
      { label: "Dec", value: 20.9 },
      { label: "Jan", value: 21.3 },
      { label: "Feb", value: 21.8 },
      { label: "Mar", value: 23.5 },
      { label: "Apr", value: 22.7 },
      { label: "May", value: 24.4 },
      { label: "Jun", value: 24.2 },
      { label: "Jul", value: 24.8 },
    ],
  },
  {
    id: "portfolio-on-track",
    label: "Projects on track",
    value: 73.3,
    formattedValue: "73%",
    format: "percent",
    change: 6.6,
    changeLabel: "+6.6 pts",
    trend: "up",
    favorable: true,
    comparisonLabel: "vs. last review",
    target: 80,
    formattedTarget: "80% target",
    targetProgress: 91.6,
    description: "11 of 15 active initiatives are on track; four need attention.",
    sparkline: [
      { label: "W20", value: 62 },
      { label: "W21", value: 64 },
      { label: "W22", value: 64 },
      { label: "W23", value: 67 },
      { label: "W24", value: 69 },
      { label: "W25", value: 67 },
      { label: "W26", value: 71 },
      { label: "W27", value: 73.3 },
    ],
  },
  {
    id: "overdue-tasks",
    label: "Overdue tasks",
    value: 7,
    formattedValue: "7",
    format: "number",
    change: -36.4,
    changeLabel: "−4 this week",
    trend: "down",
    favorable: true,
    comparisonLabel: "vs. last Friday",
    target: 5,
    formattedTarget: "≤5 target",
    targetProgress: 71.4,
    description: "Three overdue items are blocking critical-path work.",
    sparkline: [
      { label: "W20", value: 15 },
      { label: "W21", value: 14 },
      { label: "W22", value: 16 },
      { label: "W23", value: 13 },
      { label: "W24", value: 12 },
      { label: "W25", value: 11 },
      { label: "W26", value: 11 },
      { label: "W27", value: 7 },
    ],
  },
];

export const monthlyFinancials: MonthlyFinancialDatum[] = [
  { month: "2026-01", monthLabel: "Jan", revenue: 2_260_000, operatingCost: 1_790_000, revenueTarget: 2_250_000, priorYearRevenue: 2_050_000, isForecast: false },
  { month: "2026-02", monthLabel: "Feb", revenue: 2_380_000, operatingCost: 1_860_000, revenueTarget: 2_320_000, priorYearRevenue: 2_120_000, isForecast: false },
  { month: "2026-03", monthLabel: "Mar", revenue: 2_510_000, operatingCost: 1_920_000, revenueTarget: 2_450_000, priorYearRevenue: 2_220_000, isForecast: false },
  { month: "2026-04", monthLabel: "Apr", revenue: 2_470_000, operatingCost: 1_910_000, revenueTarget: 2_500_000, priorYearRevenue: 2_190_000, isForecast: false },
  { month: "2026-05", monthLabel: "May", revenue: 2_660_000, operatingCost: 2_010_000, revenueTarget: 2_580_000, priorYearRevenue: 2_330_000, isForecast: false },
  { month: "2026-06", monthLabel: "Jun", revenue: 2_730_000, operatingCost: 2_070_000, revenueTarget: 2_670_000, priorYearRevenue: 2_440_000, isForecast: false },
  { month: "2026-07", monthLabel: "Jul", revenue: 2_840_000, operatingCost: 2_136_000, revenueTarget: 2_750_000, priorYearRevenue: 2_526_000, isForecast: false },
  { month: "2026-08", monthLabel: "Aug", revenue: 2_910_000, operatingCost: 2_170_000, revenueTarget: 2_830_000, priorYearRevenue: 2_570_000, isForecast: true },
  { month: "2026-09", monthLabel: "Sep", revenue: 3_020_000, operatingCost: 2_235_000, revenueTarget: 2_950_000, priorYearRevenue: 2_680_000, isForecast: true },
  { month: "2026-10", monthLabel: "Oct", revenue: 3_110_000, operatingCost: 2_290_000, revenueTarget: 3_080_000, priorYearRevenue: 2_770_000, isForecast: true },
  { month: "2026-11", monthLabel: "Nov", revenue: 3_180_000, operatingCost: 2_325_000, revenueTarget: 3_150_000, priorYearRevenue: 2_830_000, isForecast: true },
  { month: "2026-12", monthLabel: "Dec", revenue: 3_340_000, operatingCost: 2_430_000, revenueTarget: 3_290_000, priorYearRevenue: 2_960_000, isForecast: true },
];

export const workloadByDepartment: WorkloadDatum[] = [
  { departmentId: "operations", capacityHours: 1_680, allocatedHours: 1_546, availableHours: 134, utilization: 92, activeProjects: 3, openRoles: 4, status: "at-risk" },
  { departmentId: "finance", capacityHours: 720, allocatedHours: 605, availableHours: 115, utilization: 84, activeProjects: 2, openRoles: 1, status: "healthy" },
  { departmentId: "sales", capacityHours: 1_520, allocatedHours: 1_368, availableHours: 152, utilization: 90, activeProjects: 2, openRoles: 5, status: "watch" },
  { departmentId: "product", capacityHours: 1_240, allocatedHours: 1_116, availableHours: 124, utilization: 90, activeProjects: 3, openRoles: 2, status: "watch" },
  { departmentId: "technology", capacityHours: 1_560, allocatedHours: 1_482, availableHours: 78, utilization: 95, activeProjects: 3, openRoles: 6, status: "critical" },
  { departmentId: "people", capacityHours: 640, allocatedHours: 461, availableHours: 179, utilization: 72, activeProjects: 2, openRoles: 0, status: "healthy" },
];

export const budgetByDepartment: BudgetDatum[] = [
  { departmentId: "operations", budget: 5_200_000, actual: 3_080_000, committed: 1_100_000, forecast: 5_050_000, variance: 150_000, variancePercent: 2.9, status: "healthy" },
  { departmentId: "finance", budget: 2_400_000, actual: 1_310_000, committed: 410_000, forecast: 2_280_000, variance: 120_000, variancePercent: 5, status: "healthy" },
  { departmentId: "sales", budget: 4_800_000, actual: 2_920_000, committed: 900_000, forecast: 4_720_000, variance: 80_000, variancePercent: 1.7, status: "healthy" },
  { departmentId: "product", budget: 6_100_000, actual: 3_470_000, committed: 1_360_000, forecast: 6_220_000, variance: -120_000, variancePercent: -2, status: "watch" },
  { departmentId: "technology", budget: 7_400_000, actual: 4_340_000, committed: 1_650_000, forecast: 7_550_000, variance: -150_000, variancePercent: -2, status: "at-risk" },
  { departmentId: "people", budget: 2_100_000, actual: 1_260_000, committed: 380_000, forecast: 2_040_000, variance: 60_000, variancePercent: 2.9, status: "healthy" },
];

export const projects: Project[] = [
  {
    id: "project-fulfillment-velocity",
    code: "OPS-142",
    name: "Fulfillment Velocity",
    summary: "Reduce median order-to-delivery time from 4.8 to 3.5 days across core markets.",
    departmentId: "operations",
    owner: { ...getPerson("person-lena"), allocation: 80 },
    status: "at-risk",
    priority: "urgent",
    progress: 62,
    healthScore: 58,
    budget: 1_250_000,
    spent: 880_000,
    startDate: "2026-02-02",
    targetDate: "2026-09-18",
    teamSize: 11,
    openTasks: 18,
    overdueTasks: 2,
    riskCount: 2,
    tags: ["customer", "logistics", "automation"],
    lastUpdatedAt: "2026-07-17T08:42:00+02:00",
  },
  {
    id: "project-service-quality",
    code: "OPS-155",
    name: "Service Quality Control",
    summary: "Standardize case review and raise first-contact resolution above 81%.",
    departmentId: "operations",
    owner: { ...getPerson("person-isabel"), allocation: 65 },
    status: "on-track",
    priority: "high",
    progress: 55,
    healthScore: 87,
    budget: 620_000,
    spent: 320_000,
    startDate: "2026-04-06",
    targetDate: "2026-10-30",
    teamSize: 7,
    openTasks: 11,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["quality", "customer", "enablement"],
    lastUpdatedAt: "2026-07-16T16:15:00+02:00",
  },
  {
    id: "project-vendor-network",
    code: "OPS-163",
    name: "Vendor Network Reset",
    summary: "Consolidate strategic suppliers and introduce quarterly scorecards for top spend categories.",
    departmentId: "operations",
    owner: { ...getPerson("person-olivia"), allocation: 55 },
    status: "on-track",
    priority: "medium",
    progress: 49,
    healthScore: 82,
    budget: 840_000,
    spent: 480_000,
    startDate: "2026-03-16",
    targetDate: "2026-11-13",
    teamSize: 6,
    openTasks: 9,
    overdueTasks: 0,
    riskCount: 1,
    tags: ["procurement", "savings", "vendors"],
    lastUpdatedAt: "2026-07-15T12:20:00+02:00",
  },
  {
    id: "project-erp-consolidation",
    code: "FIN-088",
    name: "ERP Consolidation",
    summary: "Migrate four regional ledgers into a single global chart of accounts and close process.",
    departmentId: "finance",
    owner: { ...getPerson("person-daniel"), allocation: 90 },
    status: "at-risk",
    priority: "urgent",
    progress: 68,
    healthScore: 61,
    budget: 1_800_000,
    spent: 1_260_000,
    startDate: "2025-11-03",
    targetDate: "2026-09-30",
    teamSize: 14,
    openTasks: 22,
    overdueTasks: 2,
    riskCount: 2,
    tags: ["finance", "systems", "compliance"],
    lastUpdatedAt: "2026-07-17T07:55:00+02:00",
  },
  {
    id: "project-cash-visibility",
    code: "FIN-101",
    name: "Cash Visibility",
    summary: "Deliver a daily thirteen-week cash position and automated variance commentary.",
    departmentId: "finance",
    owner: { ...getPerson("person-samuel"), allocation: 60 },
    status: "on-track",
    priority: "high",
    progress: 58,
    healthScore: 89,
    budget: 550_000,
    spent: 310_000,
    startDate: "2026-04-20",
    targetDate: "2026-10-16",
    teamSize: 5,
    openTasks: 8,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["treasury", "forecasting", "automation"],
    lastUpdatedAt: "2026-07-16T14:10:00+02:00",
  },
  {
    id: "project-enterprise-expansion",
    code: "REV-214",
    name: "Enterprise Expansion",
    summary: "Build repeatable account plays for the 120 highest-potential enterprise prospects.",
    departmentId: "sales",
    owner: { ...getPerson("person-amara"), allocation: 75 },
    status: "on-track",
    priority: "high",
    progress: 47,
    healthScore: 85,
    budget: 1_450_000,
    spent: 720_000,
    startDate: "2026-03-02",
    targetDate: "2026-12-11",
    teamSize: 12,
    openTasks: 17,
    overdueTasks: 0,
    riskCount: 1,
    tags: ["growth", "enterprise", "go-to-market"],
    lastUpdatedAt: "2026-07-16T18:05:00+02:00",
  },
  {
    id: "project-revenue-intelligence",
    code: "REV-226",
    name: "Revenue Intelligence",
    summary: "Unify pipeline signals and improve quarterly forecast accuracy to within five percent.",
    departmentId: "sales",
    owner: { ...getPerson("person-hana"), allocation: 70 },
    status: "on-track",
    priority: "high",
    progress: 61,
    healthScore: 80,
    budget: 780_000,
    spent: 460_000,
    startDate: "2026-02-23",
    targetDate: "2026-09-25",
    teamSize: 8,
    openTasks: 13,
    overdueTasks: 1,
    riskCount: 1,
    tags: ["analytics", "forecasting", "data"],
    lastUpdatedAt: "2026-07-17T08:10:00+02:00",
  },
  {
    id: "project-partner-acceleration",
    code: "REV-197",
    name: "Partner Acceleration",
    summary: "Launch tiered partner incentives and a shared lead-routing operating model.",
    departmentId: "sales",
    owner: { ...getPerson("person-priya"), allocation: 25 },
    status: "completed",
    priority: "medium",
    progress: 100,
    healthScore: 94,
    budget: 660_000,
    spent: 640_000,
    startDate: "2025-12-08",
    targetDate: "2026-07-10",
    teamSize: 6,
    openTasks: 0,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["partners", "growth", "launch"],
    lastUpdatedAt: "2026-07-10T17:30:00+02:00",
  },
  {
    id: "project-atlas",
    code: "PRD-302",
    name: "Atlas Platform Revamp",
    summary: "Rebuild the core workspace navigation and permissions for multi-entity customers.",
    departmentId: "product",
    owner: { ...getPerson("person-theo"), allocation: 85 },
    status: "on-track",
    priority: "urgent",
    progress: 59,
    healthScore: 86,
    budget: 2_350_000,
    spent: 1_340_000,
    startDate: "2026-01-12",
    targetDate: "2026-11-20",
    teamSize: 16,
    openTasks: 26,
    overdueTasks: 0,
    riskCount: 1,
    tags: ["platform", "enterprise", "experience"],
    lastUpdatedAt: "2026-07-17T09:02:00+02:00",
  },
  {
    id: "project-mobile-approvals",
    code: "PRD-318",
    name: "Mobile Approvals",
    summary: "Ship secure mobile review and approval flows for finance and operations leaders.",
    departmentId: "product",
    owner: { ...getPerson("person-mateo"), allocation: 75 },
    status: "at-risk",
    priority: "high",
    progress: 71,
    healthScore: 64,
    budget: 1_120_000,
    spent: 780_000,
    startDate: "2026-02-09",
    targetDate: "2026-08-28",
    teamSize: 9,
    openTasks: 14,
    overdueTasks: 1,
    riskCount: 1,
    tags: ["mobile", "workflow", "security"],
    lastUpdatedAt: "2026-07-16T19:40:00+02:00",
  },
  {
    id: "project-pricing-lab",
    code: "PRD-329",
    name: "Pricing Experiment Lab",
    summary: "Create governed tooling to test packaging and price sensitivity by segment.",
    departmentId: "product",
    owner: { ...getPerson("person-jonas"), allocation: 30 },
    status: "on-track",
    priority: "medium",
    progress: 43,
    healthScore: 83,
    budget: 680_000,
    spent: 290_000,
    startDate: "2026-05-04",
    targetDate: "2026-12-04",
    teamSize: 6,
    openTasks: 10,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["pricing", "experimentation", "growth"],
    lastUpdatedAt: "2026-07-15T15:25:00+02:00",
  },
  {
    id: "project-data-foundation",
    code: "TEC-411",
    name: "Data Foundation",
    summary: "Move analytical workloads to governed domain models with lineage and quality controls.",
    departmentId: "technology",
    owner: { ...getPerson("person-noah"), allocation: 95 },
    status: "critical",
    priority: "urgent",
    progress: 66,
    healthScore: 42,
    budget: 2_750_000,
    spent: 2_160_000,
    startDate: "2025-10-06",
    targetDate: "2026-09-11",
    teamSize: 18,
    openTasks: 31,
    overdueTasks: 1,
    riskCount: 3,
    tags: ["data", "platform", "governance"],
    lastUpdatedAt: "2026-07-17T08:55:00+02:00",
  },
  {
    id: "project-identity-modernization",
    code: "TEC-426",
    name: "Identity Modernization",
    summary: "Consolidate authentication, automate access reviews, and remove legacy identity paths.",
    departmentId: "technology",
    owner: { ...getPerson("person-viktor"), allocation: 70 },
    status: "on-track",
    priority: "high",
    progress: 54,
    healthScore: 88,
    budget: 1_400_000,
    spent: 710_000,
    startDate: "2026-03-09",
    targetDate: "2026-11-06",
    teamSize: 10,
    openTasks: 16,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["security", "identity", "compliance"],
    lastUpdatedAt: "2026-07-16T17:05:00+02:00",
  },
  {
    id: "project-observability",
    code: "TEC-433",
    name: "Observability Uplift",
    summary: "Cut detection time for priority incidents through unified service-level telemetry.",
    departmentId: "technology",
    owner: { ...getPerson("person-aisha"), allocation: 35 },
    status: "on-track",
    priority: "high",
    progress: 57,
    healthScore: 84,
    budget: 920_000,
    spent: 490_000,
    startDate: "2026-04-13",
    targetDate: "2026-10-23",
    teamSize: 8,
    openTasks: 12,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["reliability", "platform", "monitoring"],
    lastUpdatedAt: "2026-07-16T13:48:00+02:00",
  },
  {
    id: "project-leadership-academy",
    code: "PPL-074",
    name: "Leadership Academy",
    summary: "Equip first-line managers with a common operating cadence and coaching toolkit.",
    departmentId: "people",
    owner: { ...getPerson("person-mei"), allocation: 60 },
    status: "on-track",
    priority: "medium",
    progress: 51,
    healthScore: 91,
    budget: 480_000,
    spent: 220_000,
    startDate: "2026-04-27",
    targetDate: "2026-11-27",
    teamSize: 5,
    openTasks: 7,
    overdueTasks: 0,
    riskCount: 0,
    tags: ["leadership", "learning", "culture"],
    lastUpdatedAt: "2026-07-15T11:30:00+02:00",
  },
  {
    id: "project-talent-intelligence",
    code: "PPL-081",
    name: "Talent Intelligence",
    summary: "Combine skills, mobility, and workforce planning signals into one decision workspace.",
    departmentId: "people",
    owner: { ...getPerson("person-sofia"), allocation: 35 },
    status: "on-track",
    priority: "medium",
    progress: 46,
    healthScore: 86,
    budget: 740_000,
    spent: 350_000,
    startDate: "2026-05-11",
    targetDate: "2026-12-18",
    teamSize: 7,
    openTasks: 10,
    overdueTasks: 0,
    riskCount: 1,
    tags: ["workforce", "analytics", "planning"],
    lastUpdatedAt: "2026-07-16T10:45:00+02:00",
  },
];

const portfolioStatusDetails: Array<{
  status: ProjectStatus;
  label: string;
  color: string;
}> = [
  { status: "on-track", label: "On track", color: "#22C55E" },
  { status: "at-risk", label: "At risk", color: "#F59E0B" },
  { status: "critical", label: "Critical", color: "#EF4444" },
  { status: "completed", label: "Completed", color: "#64748B" },
];

export const projectPortfolio: PortfolioSlice[] = portfolioStatusDetails.map(({ status, label, color }) => {
  const matchingProjects = projects.filter((project) => project.status === status);
  return {
    status,
    label,
    color,
    count: matchingProjects.length,
    budget: matchingProjects.reduce((total, project) => total + project.budget, 0),
    spent: matchingProjects.reduce((total, project) => total + project.spent, 0),
  };
});

export const heatmapMetrics: HeatmapMetric[] = [
  { id: "delivery", label: "Delivery", description: "Schedule and milestone reliability" },
  { id: "budget", label: "Budget", description: "Forecast performance against annual plan" },
  { id: "capacity", label: "Capacity", description: "Sustainable workload and available capacity" },
  { id: "quality", label: "Quality", description: "Output quality and operational defect rate" },
  { id: "engagement", label: "Engagement", description: "Team pulse and retention indicators" },
];

const scoreToHealth = (value: number): HealthStatus => {
  if (value >= 85) return "healthy";
  if (value >= 75) return "watch";
  if (value >= 60) return "at-risk";
  return "critical";
};

const heatmapCell = (
  departmentId: HeatmapCell["departmentId"],
  metricId: HeatmapCell["metricId"],
  value: number,
  note: string,
): HeatmapCell => ({ departmentId, metricId, value, status: scoreToHealth(value), note });

export const performanceHeatmap: HeatmapCell[] = [
  heatmapCell("operations", "delivery", 68, "Carrier variance is adding 0.6 days to delivery."),
  heatmapCell("operations", "budget", 88, "Forecast is $150K below annual plan."),
  heatmapCell("operations", "capacity", 64, "Utilization has remained above 90% for five weeks."),
  heatmapCell("operations", "quality", 79, "First-contact resolution improved to 78%."),
  heatmapCell("operations", "engagement", 82, "Pulse score is stable with a small workload dip."),
  heatmapCell("finance", "delivery", 72, "ERP cutover readiness is behind the baseline."),
  heatmapCell("finance", "budget", 92, "Forecast is five percent favorable to plan."),
  heatmapCell("finance", "capacity", 86, "Quarter-close coverage is fully staffed."),
  heatmapCell("finance", "quality", 88, "Reconciliation exceptions fell 18% this month."),
  heatmapCell("finance", "engagement", 80, "Transformation workload remains the main concern."),
  heatmapCell("sales", "delivery", 84, "Pipeline programs are within one week of plan."),
  heatmapCell("sales", "budget", 89, "Program spend is tracking $80K below forecast."),
  heatmapCell("sales", "capacity", 74, "Enterprise coverage is tight in two regions."),
  heatmapCell("sales", "quality", 78, "Forecast hygiene improved but still varies by region."),
  heatmapCell("sales", "engagement", 87, "Team pulse rose after territory adjustments."),
  heatmapCell("product", "delivery", 77, "Mobile approvals is masking strong Atlas delivery."),
  heatmapCell("product", "budget", 73, "Two external research packages are above plan."),
  heatmapCell("product", "capacity", 71, "Design and mobile engineering are fully allocated."),
  heatmapCell("product", "quality", 90, "Escaped defects remain below the quarterly target."),
  heatmapCell("product", "engagement", 85, "Product team pulse is unchanged at a healthy level."),
  heatmapCell("technology", "delivery", 55, "Data Foundation is three weeks behind its recovery plan."),
  heatmapCell("technology", "budget", 69, "Platform forecast is $150K above annual plan."),
  heatmapCell("technology", "capacity", 52, "Utilization is 95% with six priority roles open."),
  heatmapCell("technology", "quality", 76, "Reliability is improving, but data freshness misses persist."),
  heatmapCell("technology", "engagement", 70, "Sustained critical-path work reduced the pulse score."),
  heatmapCell("people", "delivery", 89, "Both strategic programs are tracking to December milestones."),
  heatmapCell("people", "budget", 91, "Forecast is $60K favorable to annual plan."),
  heatmapCell("people", "capacity", 94, "Capacity is available for the Q4 talent cycle."),
  heatmapCell("people", "quality", 86, "Manager cohort satisfaction is 4.6 out of five."),
  heatmapCell("people", "engagement", 92, "Company pulse participation reached 88%."),
];

export const tasks: Task[] = [
  {
    id: "task-001",
    title: "Approve carrier API fallback plan",
    projectId: "project-fulfillment-velocity",
    departmentId: "operations",
    assignee: getPerson("person-lena"),
    status: "blocked",
    priority: "urgent",
    dueDate: "2026-07-14",
    estimateHours: 6,
    labels: ["critical-path", "integration"],
    isOverdue: true,
  },
  {
    id: "task-002",
    title: "Validate route-time baseline with regional leads",
    projectId: "project-fulfillment-velocity",
    departmentId: "operations",
    assignee: getPerson("person-olivia"),
    status: "in-progress",
    priority: "high",
    dueDate: "2026-07-16",
    estimateHours: 8,
    labels: ["analytics", "regional"],
    isOverdue: true,
  },
  {
    id: "task-003",
    title: "Sign off close-management playbook",
    projectId: "project-erp-consolidation",
    departmentId: "finance",
    assignee: getPerson("person-marcus"),
    status: "blocked",
    priority: "urgent",
    dueDate: "2026-07-15",
    estimateHours: 4,
    labels: ["cutover", "approval"],
    isOverdue: true,
  },
  {
    id: "task-004",
    title: "Clear opening-balance reconciliation exceptions",
    projectId: "project-erp-consolidation",
    departmentId: "finance",
    assignee: getPerson("person-samuel"),
    status: "in-review",
    priority: "high",
    dueDate: "2026-07-13",
    estimateHours: 12,
    labels: ["data", "reconciliation"],
    isOverdue: true,
  },
  {
    id: "task-005",
    title: "Calibrate late-stage forecast scoring",
    projectId: "project-revenue-intelligence",
    departmentId: "sales",
    assignee: getPerson("person-hana"),
    status: "in-progress",
    priority: "high",
    dueDate: "2026-07-16",
    estimateHours: 7,
    labels: ["forecast", "model"],
    isOverdue: true,
  },
  {
    id: "task-006",
    title: "Resolve mobile penetration-test findings",
    projectId: "project-mobile-approvals",
    departmentId: "product",
    assignee: getPerson("person-mateo"),
    status: "in-progress",
    priority: "urgent",
    dueDate: "2026-07-15",
    estimateHours: 16,
    labels: ["security", "release-blocker"],
    isOverdue: true,
  },
  {
    id: "task-007",
    title: "Backfill freshness checks for finance models",
    projectId: "project-data-foundation",
    departmentId: "technology",
    assignee: getPerson("person-noah"),
    status: "blocked",
    priority: "urgent",
    dueDate: "2026-07-12",
    estimateHours: 14,
    labels: ["data-quality", "critical-path"],
    isOverdue: true,
  },
  {
    id: "task-008",
    title: "Publish supplier scorecard v2",
    projectId: "project-vendor-network",
    departmentId: "operations",
    assignee: getPerson("person-olivia"),
    status: "in-review",
    priority: "medium",
    dueDate: "2026-07-20",
    estimateHours: 5,
    labels: ["vendors", "reporting"],
    isOverdue: false,
  },
  {
    id: "task-009",
    title: "Complete daily cash variance prototype",
    projectId: "project-cash-visibility",
    departmentId: "finance",
    assignee: getPerson("person-samuel"),
    status: "in-progress",
    priority: "high",
    dueDate: "2026-07-21",
    estimateHours: 10,
    labels: ["prototype", "treasury"],
    isOverdue: false,
  },
  {
    id: "task-010",
    title: "Review top-25 account expansion plays",
    projectId: "project-enterprise-expansion",
    departmentId: "sales",
    assignee: getPerson("person-amara"),
    status: "in-progress",
    priority: "high",
    dueDate: "2026-07-22",
    estimateHours: 9,
    labels: ["enterprise", "pipeline"],
    isOverdue: false,
  },
  {
    id: "task-011",
    title: "Finalize workspace permission prototype",
    projectId: "project-atlas",
    departmentId: "product",
    assignee: getPerson("person-theo"),
    status: "in-review",
    priority: "high",
    dueDate: "2026-07-20",
    estimateHours: 13,
    labels: ["permissions", "prototype"],
    isOverdue: false,
  },
  {
    id: "task-012",
    title: "Run pricing guardrail dry run",
    projectId: "project-pricing-lab",
    departmentId: "product",
    assignee: getPerson("person-jonas"),
    status: "todo",
    priority: "medium",
    dueDate: "2026-07-24",
    estimateHours: 6,
    labels: ["pricing", "governance"],
    isOverdue: false,
  },
  {
    id: "task-013",
    title: "Load-test lineage service at quarter-close volume",
    projectId: "project-data-foundation",
    departmentId: "technology",
    assignee: getPerson("person-viktor"),
    status: "todo",
    priority: "high",
    dueDate: "2026-07-23",
    estimateHours: 12,
    labels: ["performance", "data"],
    isOverdue: false,
  },
  {
    id: "task-014",
    title: "Complete privileged-access review automation",
    projectId: "project-identity-modernization",
    departmentId: "technology",
    assignee: getPerson("person-viktor"),
    status: "in-progress",
    priority: "high",
    dueDate: "2026-07-27",
    estimateHours: 18,
    labels: ["security", "automation"],
    isOverdue: false,
  },
  {
    id: "task-015",
    title: "Approve service-level objective catalog",
    projectId: "project-observability",
    departmentId: "technology",
    assignee: getPerson("person-aisha"),
    status: "in-review",
    priority: "high",
    dueDate: "2026-07-24",
    estimateHours: 5,
    labels: ["reliability", "governance"],
    isOverdue: false,
  },
  {
    id: "task-016",
    title: "Facilitate manager cohort two kickoff",
    projectId: "project-leadership-academy",
    departmentId: "people",
    assignee: getPerson("person-mei"),
    status: "todo",
    priority: "medium",
    dueDate: "2026-07-28",
    estimateHours: 4,
    labels: ["learning", "event"],
    isOverdue: false,
  },
  {
    id: "task-017",
    title: "Map critical skills to FY27 workforce scenarios",
    projectId: "project-talent-intelligence",
    departmentId: "people",
    assignee: getPerson("person-sofia"),
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-07-30",
    estimateHours: 9,
    labels: ["skills", "planning"],
    isOverdue: false,
  },
  {
    id: "task-018",
    title: "Archive partner launch readiness checklist",
    projectId: "project-partner-acceleration",
    departmentId: "sales",
    assignee: getPerson("person-priya"),
    status: "done",
    priority: "low",
    dueDate: "2026-07-10",
    completedAt: "2026-07-10T15:20:00+02:00",
    estimateHours: 2,
    labels: ["launch", "governance"],
    isOverdue: false,
  },
];

export const taskTrends: TaskTrendDatum[] = [
  { week: "2026-W20", weekLabel: "May 11", created: 48, completed: 42, overdue: 15 },
  { week: "2026-W21", weekLabel: "May 18", created: 44, completed: 46, overdue: 14 },
  { week: "2026-W22", weekLabel: "May 25", created: 51, completed: 43, overdue: 16 },
  { week: "2026-W23", weekLabel: "Jun 1", created: 46, completed: 49, overdue: 13 },
  { week: "2026-W24", weekLabel: "Jun 8", created: 43, completed: 47, overdue: 12 },
  { week: "2026-W25", weekLabel: "Jun 15", created: 45, completed: 48, overdue: 11 },
  { week: "2026-W26", weekLabel: "Jun 22", created: 39, completed: 42, overdue: 11 },
  { week: "2026-W27", weekLabel: "Jun 29", created: 41, completed: 49, overdue: 7 },
];

export const risks: Risk[] = [
  {
    id: "risk-001",
    title: "Carrier routing API misses peak-volume SLA",
    description: "The primary carrier API is timing out above 4,000 requests per minute, delaying automated routing.",
    severity: "critical",
    status: "mitigating",
    trend: "worsening",
    departmentId: "operations",
    projectId: "project-fulfillment-velocity",
    owner: getPerson("person-lena"),
    detectedAt: "2026-07-14T09:15:00+02:00",
    reviewDate: "2026-07-18",
    likelihood: 5,
    impact: 5,
    mitigation: "Route overflow through the secondary provider and cap non-priority retries.",
  },
  {
    id: "risk-002",
    title: "Regional rollout baseline is incomplete",
    description: "Two regional teams have not validated transit-time baselines needed for the September rollout decision.",
    severity: "medium",
    status: "monitoring",
    trend: "stable",
    departmentId: "operations",
    projectId: "project-fulfillment-velocity",
    owner: getPerson("person-olivia"),
    detectedAt: "2026-07-11T14:40:00+02:00",
    reviewDate: "2026-07-21",
    likelihood: 3,
    impact: 3,
    mitigation: "Use the central analytics baseline if regional sign-off misses July 20.",
  },
  {
    id: "risk-003",
    title: "Supplier concentration remains above policy",
    description: "One logistics supplier still represents 41% of category spend against a 30% policy ceiling.",
    severity: "medium",
    status: "mitigating",
    trend: "improving",
    departmentId: "operations",
    projectId: "project-vendor-network",
    owner: getPerson("person-olivia"),
    detectedAt: "2026-06-29T11:10:00+02:00",
    reviewDate: "2026-07-24",
    likelihood: 3,
    impact: 4,
    mitigation: "Move the next two sourcing waves to qualified secondary suppliers.",
  },
  {
    id: "risk-004",
    title: "ERP opening balances have unresolved exceptions",
    description: "Thirty-seven intercompany exceptions prevent final cutover rehearsal sign-off.",
    severity: "high",
    status: "mitigating",
    trend: "improving",
    departmentId: "finance",
    projectId: "project-erp-consolidation",
    owner: getPerson("person-daniel"),
    detectedAt: "2026-07-09T08:30:00+02:00",
    reviewDate: "2026-07-18",
    likelihood: 4,
    impact: 5,
    mitigation: "Run a daily exception room with regional controllers until fewer than five items remain.",
  },
  {
    id: "risk-005",
    title: "Close-process adoption is uneven",
    description: "Two regions are still using legacy close checklists, creating duplicate controls during rehearsal.",
    severity: "medium",
    status: "monitoring",
    trend: "stable",
    departmentId: "finance",
    projectId: "project-erp-consolidation",
    owner: getPerson("person-samuel"),
    detectedAt: "2026-07-07T16:05:00+02:00",
    reviewDate: "2026-07-22",
    likelihood: 3,
    impact: 3,
    mitigation: "Require controller sign-off on the unified playbook before rehearsal two.",
  },
  {
    id: "risk-006",
    title: "Enterprise coverage gap in DACH",
    description: "A vacant strategic account role leaves nine target accounts without an assigned executive sponsor.",
    severity: "medium",
    status: "mitigating",
    trend: "stable",
    departmentId: "sales",
    projectId: "project-enterprise-expansion",
    owner: getPerson("person-amara"),
    detectedAt: "2026-07-03T10:00:00+02:00",
    reviewDate: "2026-07-27",
    likelihood: 3,
    impact: 3,
    mitigation: "Temporarily distribute accounts across the regional director and two senior sellers.",
  },
  {
    id: "risk-007",
    title: "Forecast model underweights renewal slippage",
    description: "Back-testing shows a seven-point accuracy gap for late-stage renewals with legal redlines.",
    severity: "high",
    status: "mitigating",
    trend: "improving",
    departmentId: "sales",
    projectId: "project-revenue-intelligence",
    owner: getPerson("person-hana"),
    detectedAt: "2026-07-08T13:20:00+02:00",
    reviewDate: "2026-07-21",
    likelihood: 4,
    impact: 4,
    mitigation: "Add legal-stage age and redline count to the scoring rules before Q3 commit.",
  },
  {
    id: "risk-008",
    title: "Permissions model depends on delayed identity contract",
    description: "Atlas cannot finalize delegated admin flows until the new role contract is stable.",
    severity: "medium",
    status: "monitoring",
    trend: "stable",
    departmentId: "product",
    projectId: "project-atlas",
    owner: getPerson("person-theo"),
    detectedAt: "2026-07-10T15:45:00+02:00",
    reviewDate: "2026-07-23",
    likelihood: 3,
    impact: 4,
    mitigation: "Ship the prototype against a versioned adapter while the identity contract is finalized.",
  },
  {
    id: "risk-009",
    title: "Mobile security findings block release candidate",
    description: "Two high-severity penetration-test findings remain open in offline approval storage.",
    severity: "high",
    status: "mitigating",
    trend: "improving",
    departmentId: "product",
    projectId: "project-mobile-approvals",
    owner: getPerson("person-mateo"),
    detectedAt: "2026-07-13T17:30:00+02:00",
    reviewDate: "2026-07-20",
    likelihood: 4,
    impact: 5,
    mitigation: "Disable offline persistence for the first release and complete the encrypted-store patch.",
  },
  {
    id: "risk-010",
    title: "Data migration recovery plan is three weeks late",
    description: "Historical finance domains are taking 1.8× longer to validate than the approved recovery plan.",
    severity: "critical",
    status: "mitigating",
    trend: "worsening",
    departmentId: "technology",
    projectId: "project-data-foundation",
    owner: getPerson("person-noah"),
    detectedAt: "2026-07-02T08:05:00+02:00",
    reviewDate: "2026-07-18",
    likelihood: 5,
    impact: 5,
    mitigation: "Move two platform engineers to validation and defer the lower-value support domain.",
  },
  {
    id: "risk-011",
    title: "Freshness checks miss finance service levels",
    description: "Five tier-one models exceeded the 90-minute freshness objective twice this week.",
    severity: "high",
    status: "mitigating",
    trend: "stable",
    departmentId: "technology",
    projectId: "project-data-foundation",
    owner: getPerson("person-viktor"),
    detectedAt: "2026-07-12T06:50:00+02:00",
    reviewDate: "2026-07-19",
    likelihood: 4,
    impact: 4,
    mitigation: "Backfill incremental checks and prioritize quarter-close models in the scheduler.",
  },
  {
    id: "risk-012",
    title: "Data platform capacity is below recovery need",
    description: "The team is at 97% allocation after incident coverage and has no buffer for migration defects.",
    severity: "high",
    status: "open",
    trend: "worsening",
    departmentId: "technology",
    projectId: "project-data-foundation",
    owner: getPerson("person-aisha"),
    detectedAt: "2026-07-15T12:00:00+02:00",
    reviewDate: "2026-07-18",
    likelihood: 5,
    impact: 4,
    mitigation: "Approve a four-week reliability rotation and pause two non-critical platform upgrades.",
  },
  {
    id: "risk-013",
    title: "Skills taxonomy coverage is incomplete",
    description: "Twenty-two percent of specialist roles still lack validated proficiency definitions.",
    severity: "low",
    status: "monitoring",
    trend: "improving",
    departmentId: "people",
    projectId: "project-talent-intelligence",
    owner: getPerson("person-sofia"),
    detectedAt: "2026-06-26T09:30:00+02:00",
    reviewDate: "2026-07-31",
    likelihood: 2,
    impact: 2,
    mitigation: "Prioritize roles used in FY27 workforce scenarios and defer long-tail validation.",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "activity-001",
    type: "risk-raised",
    actor: getPerson("person-aisha"),
    title: "Capacity risk escalated",
    description: "Raised Data Platform capacity to high severity after the weekly allocation review.",
    occurredAt: "2026-07-17T09:12:00+02:00",
    departmentId: "technology",
    projectId: "project-data-foundation",
    metadata: { severity: "high", utilization: 97 },
  },
  {
    id: "activity-002",
    type: "project-update",
    actor: getPerson("person-lena"),
    title: "Fulfillment recovery plan updated",
    description: "Added the secondary routing provider and moved the decision gate to July 18.",
    occurredAt: "2026-07-17T08:42:00+02:00",
    departmentId: "operations",
    projectId: "project-fulfillment-velocity",
    metadata: { progress: 62, healthScore: 58 },
  },
  {
    id: "activity-003",
    type: "comment",
    actor: getPerson("person-marcus"),
    title: "ERP cutover needs controller sign-off",
    description: "Requested regional controller approval before the second rehearsal begins.",
    occurredAt: "2026-07-17T08:18:00+02:00",
    departmentId: "finance",
    projectId: "project-erp-consolidation",
  },
  {
    id: "activity-004",
    type: "project-update",
    actor: getPerson("person-hana"),
    title: "Forecast back-test improved",
    description: "Renewal-slippage features reduced the accuracy gap from 7.0 to 4.8 points.",
    occurredAt: "2026-07-17T08:10:00+02:00",
    departmentId: "sales",
    projectId: "project-revenue-intelligence",
    metadata: { previousGap: 7, currentGap: 4.8 },
  },
  {
    id: "activity-005",
    type: "task-completed",
    actor: getPerson("person-theo"),
    title: "Navigation usability review completed",
    description: "The Atlas team closed all priority-one findings from the enterprise usability study.",
    occurredAt: "2026-07-16T18:32:00+02:00",
    departmentId: "product",
    projectId: "project-atlas",
    metadata: { findingsClosed: 6 },
  },
  {
    id: "activity-006",
    type: "budget-change",
    actor: getPerson("person-jonas"),
    title: "Product forecast revised",
    description: "Added $120K of external research spend to the second-half forecast.",
    occurredAt: "2026-07-16T16:48:00+02:00",
    departmentId: "product",
    metadata: { amount: 120000 },
  },
  {
    id: "activity-007",
    type: "milestone",
    actor: getPerson("person-isabel"),
    title: "Quality pilot reached 1,000 cases",
    description: "The standardized review pilot passed its sample-size milestone at 78% first-contact resolution.",
    occurredAt: "2026-07-16T15:20:00+02:00",
    departmentId: "operations",
    projectId: "project-service-quality",
    metadata: { cases: 1000, resolutionRate: 78 },
  },
  {
    id: "activity-008",
    type: "project-update",
    actor: getPerson("person-mei"),
    title: "Leadership cohort two confirmed",
    description: "Twenty-four managers accepted invitations for the July 28 kickoff.",
    occurredAt: "2026-07-16T11:05:00+02:00",
    departmentId: "people",
    projectId: "project-leadership-academy",
    metadata: { attendees: 24 },
  },
  {
    id: "activity-009",
    type: "task-completed",
    actor: getPerson("person-viktor"),
    title: "SSO migration test passed",
    description: "The identity team validated migration for the first 2,500 internal accounts.",
    occurredAt: "2026-07-16T09:44:00+02:00",
    departmentId: "technology",
    projectId: "project-identity-modernization",
    metadata: { accounts: 2500 },
  },
  {
    id: "activity-010",
    type: "milestone",
    actor: getPerson("person-priya"),
    title: "Partner Acceleration completed",
    description: "Closed the program within budget after onboarding 34 tier-one partners.",
    occurredAt: "2026-07-10T17:30:00+02:00",
    departmentId: "sales",
    projectId: "project-partner-acceleration",
    metadata: { partners: 34, budgetVariance: 20000 },
  },
];

export const deadlines: Deadline[] = [
  {
    id: "deadline-001",
    title: "Fulfillment recovery decision gate",
    date: "2026-07-18T10:00:00+02:00",
    endDate: "2026-07-18T10:45:00+02:00",
    type: "review",
    departmentId: "operations",
    projectId: "project-fulfillment-velocity",
    owner: getPerson("person-lena"),
    location: "Ops room / Zoom",
    isAllDay: false,
    status: "at-risk",
  },
  {
    id: "deadline-002",
    title: "ERP exception burn-down review",
    date: "2026-07-18T14:00:00+02:00",
    endDate: "2026-07-18T15:00:00+02:00",
    type: "review",
    departmentId: "finance",
    projectId: "project-erp-consolidation",
    owner: getPerson("person-daniel"),
    location: "Finance war room",
    isAllDay: false,
    status: "at-risk",
  },
  {
    id: "deadline-003",
    title: "Mobile security re-test",
    date: "2026-07-20T09:00:00+02:00",
    endDate: "2026-07-20T12:00:00+02:00",
    type: "review",
    departmentId: "product",
    projectId: "project-mobile-approvals",
    owner: getPerson("person-mateo"),
    location: "Remote",
    isAllDay: false,
    status: "at-risk",
  },
  {
    id: "deadline-004",
    title: "Q3 operating review",
    date: "2026-07-21T15:00:00+02:00",
    endDate: "2026-07-21T16:30:00+02:00",
    type: "review",
    departmentId: "finance",
    owner: getPerson("person-marcus"),
    location: "Executive boardroom",
    isAllDay: false,
    status: "confirmed",
  },
  {
    id: "deadline-005",
    title: "Atlas permissions milestone",
    date: "2026-07-24",
    type: "milestone",
    departmentId: "product",
    projectId: "project-atlas",
    owner: getPerson("person-theo"),
    isAllDay: true,
    status: "confirmed",
  },
  {
    id: "deadline-006",
    title: "Strategic supplier bids due",
    date: "2026-07-24T17:00:00+02:00",
    type: "payment",
    departmentId: "operations",
    projectId: "project-vendor-network",
    owner: getPerson("person-olivia"),
    isAllDay: false,
    status: "confirmed",
  },
  {
    id: "deadline-007",
    title: "Enterprise pipeline council",
    date: "2026-07-27T13:00:00+02:00",
    endDate: "2026-07-27T14:00:00+02:00",
    type: "event",
    departmentId: "sales",
    projectId: "project-enterprise-expansion",
    owner: getPerson("person-amara"),
    location: "Revenue studio",
    isAllDay: false,
    status: "confirmed",
  },
  {
    id: "deadline-008",
    title: "Leadership cohort two kickoff",
    date: "2026-07-28T09:30:00+02:00",
    endDate: "2026-07-28T12:30:00+02:00",
    type: "event",
    departmentId: "people",
    projectId: "project-leadership-academy",
    owner: getPerson("person-mei"),
    location: "Learning lab",
    isAllDay: false,
    status: "confirmed",
  },
  {
    id: "deadline-009",
    title: "Data migration recovery checkpoint",
    date: "2026-07-31T11:00:00+02:00",
    endDate: "2026-07-31T12:00:00+02:00",
    type: "milestone",
    departmentId: "technology",
    projectId: "project-data-foundation",
    owner: getPerson("person-noah"),
    location: "Platform room",
    isAllDay: false,
    status: "at-risk",
  },
  {
    id: "deadline-010",
    title: "Mobile approvals release candidate",
    date: "2026-08-07",
    type: "launch",
    departmentId: "product",
    projectId: "project-mobile-approvals",
    owner: getPerson("person-mateo"),
    isAllDay: true,
    status: "tentative",
  },
];

export const dependencyNodes: DependencyNodeData[] = [
  { id: "node-vendors", projectId: "project-vendor-network", label: "Vendor Network", departmentId: "operations", status: "on-track", progress: 49, position: { x: 0, y: 40 } },
  { id: "node-identity", projectId: "project-identity-modernization", label: "Identity", departmentId: "technology", status: "on-track", progress: 54, position: { x: 0, y: 190 } },
  { id: "node-observability", projectId: "project-observability", label: "Observability", departmentId: "technology", status: "on-track", progress: 57, position: { x: 0, y: 340 } },
  { id: "node-erp", projectId: "project-erp-consolidation", label: "ERP Consolidation", departmentId: "finance", status: "at-risk", progress: 68, position: { x: 240, y: 40 } },
  { id: "node-data", projectId: "project-data-foundation", label: "Data Foundation", departmentId: "technology", status: "critical", progress: 66, position: { x: 240, y: 260 } },
  { id: "node-fulfillment", projectId: "project-fulfillment-velocity", label: "Fulfillment", departmentId: "operations", status: "at-risk", progress: 62, position: { x: 480, y: 0 } },
  { id: "node-cash", projectId: "project-cash-visibility", label: "Cash Visibility", departmentId: "finance", status: "on-track", progress: 58, position: { x: 480, y: 120 } },
  { id: "node-atlas", projectId: "project-atlas", label: "Atlas", departmentId: "product", status: "on-track", progress: 59, position: { x: 480, y: 240 } },
  { id: "node-revenue", projectId: "project-revenue-intelligence", label: "Revenue Intelligence", departmentId: "sales", status: "on-track", progress: 61, position: { x: 480, y: 360 } },
  { id: "node-mobile", projectId: "project-mobile-approvals", label: "Mobile Approvals", departmentId: "product", status: "at-risk", progress: 71, position: { x: 720, y: 160 } },
  { id: "node-enterprise", projectId: "project-enterprise-expansion", label: "Enterprise Expansion", departmentId: "sales", status: "on-track", progress: 47, position: { x: 720, y: 360 } },
];

export const dependencyEdges: DependencyEdgeData[] = [
  { id: "edge-vendors-fulfillment", source: "node-vendors", target: "node-fulfillment", label: "carrier contracts", critical: false, lagDays: 2 },
  { id: "edge-erp-cash", source: "node-erp", target: "node-cash", label: "ledger model", critical: true, lagDays: 5 },
  { id: "edge-erp-data", source: "node-erp", target: "node-data", label: "chart of accounts", critical: true, lagDays: 0 },
  { id: "edge-observability-data", source: "node-observability", target: "node-data", label: "freshness telemetry", critical: false, lagDays: 1 },
  { id: "edge-data-cash", source: "node-data", target: "node-cash", label: "cash domains", critical: true, lagDays: 3 },
  { id: "edge-data-atlas", source: "node-data", target: "node-atlas", label: "usage model", critical: false, lagDays: 2 },
  { id: "edge-data-revenue", source: "node-data", target: "node-revenue", label: "pipeline model", critical: true, lagDays: 4 },
  { id: "edge-identity-atlas", source: "node-identity", target: "node-atlas", label: "role contract", critical: true, lagDays: 2 },
  { id: "edge-identity-mobile", source: "node-identity", target: "node-mobile", label: "device sessions", critical: false, lagDays: 1 },
  { id: "edge-atlas-mobile", source: "node-atlas", target: "node-mobile", label: "approval shell", critical: true, lagDays: 5 },
  { id: "edge-revenue-enterprise", source: "node-revenue", target: "node-enterprise", label: "account signals", critical: false, lagDays: 2 },
];

export const dashboardData = {
  snapshotAt: dashboardSnapshotAt,
  teamMembers,
  departments,
  kpis: kpiMetrics,
  financials: monthlyFinancials,
  workload: workloadByDepartment,
  budget: budgetByDepartment,
  portfolio: projectPortfolio,
  projects,
  heatmapMetrics,
  heatmap: performanceHeatmap,
  tasks,
  taskTrends,
  risks,
  activities,
  deadlines,
  dependencies: {
    nodes: dependencyNodes,
    edges: dependencyEdges,
  },
} as const;
